# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subnode_call.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12subnode_call.proto\"%\n\x14GetCandidatesRequest\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"&\n\x15GetCandidatesResponse\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x32Z\n\x12SubNodeCallService\x12\x44\n\rgetCandidates\x12\x15.GetCandidatesRequest\x1a\x16.GetCandidatesResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'subnode_call_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETCANDIDATESREQUEST']._serialized_start=22
  _globals['_GETCANDIDATESREQUEST']._serialized_end=59
  _globals['_GETCANDIDATESRESPONSE']._serialized_start=61
  _globals['_GETCANDIDATESRESPONSE']._serialized_end=99
  _globals['_SUBNODECALLSERVICE']._serialized_start=101
  _globals['_SUBNODECALLSERVICE']._serialized_end=191
# @@protoc_insertion_point(module_scope)
