name: ferderei_v2
channels:
  - bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - pytorch
  - conda-forge
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - archspec=0.2.3
  - asttokens=2.4.1
  - backcall=0.2.0
  - blas=1.0
  - boltons=23.1.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - conda=24.1.2
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - contourpy=1.1.1
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.99
  - cuda-runtime=12.1.0
  - cycler=0.12.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - deprecated=1.2.14
  - distro=1.9.0
  - executing=2.0.1
  - expat=2.6.2
  - ffmpeg=4.3
  - filelock=3.13.1
  - fmt=10.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.49.0
  - freetype=2.12.1
  - freetype-py=2.3.0
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - greenlet=3.0.3
  - grpcio=1.62.1
  - grpcio-tools=1.62.1
  - hnswlib=0.7.0
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.2
  - importlib-resources=6.3.0
  - importlib_metadata=7.0.2
  - importlib_resources=6.3.0
  - intel-openmp=2022.1.0
  - ipykernel=6.29.3
  - ipython=8.12.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - jpype1=1.5.0
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.1
  - libarchive=3.7.2
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-python=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.0.20
  - libcurand=10.3.5.119
  - libcurl=8.5.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.0
  - libgomp=13.2.0
  - libgrpc=1.62.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libmamba=1.5.7
  - libmambapy=1.5.7
  - libnghttp2=1.58.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.25
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsolv=0.7.28
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.5
  - libxslt=1.1.39
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.7
  - markupsafe=2.1.5
  - matchms=0.24.2
  - matplotlib-base=3.7.3
  - matplotlib-inline=0.1.6
  - menuinst=2.0.2
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.6
  - networkx=3.1
  - numpy=1.24.4
  - openbabel=3.1.1
  - openblas=0.3.25
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.2.1
  - packaging=24.0
  - pandas=2.0.3
  - parso=0.8.3
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pickydict=0.4.0
  - pillow=9.5.0
  - pip=24.0
  - pixman=0.43.2
  - platformdirs=4.2.0
  - pluggy=1.4.0
  - pooch=1.8.1
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - protobuf=4.25.3
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pubchempy=1.0.4
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycairo=1.26.0
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.17.2
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - pyteomics=4.7.1
  - python=3.8.18
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.8
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - rdkit=2023.09.6
  - re2=2023.09.01
  - readline=8.2
  - reportlab=4.1.0
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - rlpycairo=0.2.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - scipy=1.10.1
  - setuptools=69.2.0
  - six=1.16.0
  - sparsestack=0.4.1
  - sqlalchemy=2.0.28
  - stack_data=0.6.2
  - sympy=1.12
  - tk=8.6.13
  - torchaudio=2.2.1
  - torchtriton=2.2.0
  - torchvision=0.17.1
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.2
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - unicodedata2=15.1.0
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - wheel=0.42.0
  - wrapt=1.16.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gensim==4.3.2
      - h5py==3.11.0
      - imbalanced-learn==0.12.4
      - imblearn==0.0
      - lightning-utilities==0.10.1
      - llvmlite==0.40.1
      - lxml==4.9.4
      - multidict==6.0.5
      - numba==0.57.1
      - pytorch-lightning==2.2.1
      - scikit-learn==1.3.2
      - smart-open==7.0.1
      - spec2vec==0.8.0
      - threadpoolctl==3.3.0
      - torch-geometric==2.5.1
      - torchmetrics==1.3.1
      - yarl==1.9.4
