# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_manage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66ile_manage.proto\"@\n\x11SubmitFileRequest\x12\x0e\n\x04name\x18\x01 \x01(\tH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\n\n\x08\x66ileData\"\xb6\x01\n\x12SubmitFileResponse\x12*\n\x06result\x18\x01 \x01(\x0b\x32\x1a.SubmitFileResponse.Result\x1at\n\x06Result\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08\x66ileName\x18\x03 \x01(\t\x12\n\n\x02mw\x18\x04 \x01(\x02\x12\n\n\x02mz\x18\x05 \x01(\x0c\x12\x13\n\x0bintensities\x18\x06 \x01(\x0c\x12\x10\n\x08inchikey\x18\x07 \x01(\t\"!\n\x11\x43learCacheRequest\x12\x0c\n\x04\x64\x65sc\x18\x01 \x01(\t\"\"\n\x12\x43learCacheResponse\x12\x0c\n\x04\x64\x65sc\x18\x01 \x01(\t2\x89\x01\n\x11\x46ileManageService\x12;\n\nsubmitFile\x12\x12.SubmitFileRequest\x1a\x13.SubmitFileResponse\"\x00(\x01\x30\x01\x12\x37\n\nclearCache\x12\x12.ClearCacheRequest\x1a\x13.ClearCacheResponse\"\x00\x42%\n\x10org.jhcg.pms.apiB\x0f\x46ileManageProtoP\x00\x62\x06proto3')



_SUBMITFILEREQUEST = DESCRIPTOR.message_types_by_name['SubmitFileRequest']
_SUBMITFILERESPONSE = DESCRIPTOR.message_types_by_name['SubmitFileResponse']
_SUBMITFILERESPONSE_RESULT = _SUBMITFILERESPONSE.nested_types_by_name['Result']
_CLEARCACHEREQUEST = DESCRIPTOR.message_types_by_name['ClearCacheRequest']
_CLEARCACHERESPONSE = DESCRIPTOR.message_types_by_name['ClearCacheResponse']
SubmitFileRequest = _reflection.GeneratedProtocolMessageType('SubmitFileRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITFILEREQUEST,
  '__module__' : 'file_manage_pb2'
  # @@protoc_insertion_point(class_scope:SubmitFileRequest)
  })
_sym_db.RegisterMessage(SubmitFileRequest)

SubmitFileResponse = _reflection.GeneratedProtocolMessageType('SubmitFileResponse', (_message.Message,), {

  'Result' : _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
    'DESCRIPTOR' : _SUBMITFILERESPONSE_RESULT,
    '__module__' : 'file_manage_pb2'
    # @@protoc_insertion_point(class_scope:SubmitFileResponse.Result)
    })
  ,
  'DESCRIPTOR' : _SUBMITFILERESPONSE,
  '__module__' : 'file_manage_pb2'
  # @@protoc_insertion_point(class_scope:SubmitFileResponse)
  })
_sym_db.RegisterMessage(SubmitFileResponse)
_sym_db.RegisterMessage(SubmitFileResponse.Result)

ClearCacheRequest = _reflection.GeneratedProtocolMessageType('ClearCacheRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLEARCACHEREQUEST,
  '__module__' : 'file_manage_pb2'
  # @@protoc_insertion_point(class_scope:ClearCacheRequest)
  })
_sym_db.RegisterMessage(ClearCacheRequest)

ClearCacheResponse = _reflection.GeneratedProtocolMessageType('ClearCacheResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLEARCACHERESPONSE,
  '__module__' : 'file_manage_pb2'
  # @@protoc_insertion_point(class_scope:ClearCacheResponse)
  })
_sym_db.RegisterMessage(ClearCacheResponse)

_FILEMANAGESERVICE = DESCRIPTOR.services_by_name['FileManageService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020org.jhcg.pms.apiB\017FileManageProtoP\000'
  _SUBMITFILEREQUEST._serialized_start=21
  _SUBMITFILEREQUEST._serialized_end=85
  _SUBMITFILERESPONSE._serialized_start=88
  _SUBMITFILERESPONSE._serialized_end=270
  _SUBMITFILERESPONSE_RESULT._serialized_start=154
  _SUBMITFILERESPONSE_RESULT._serialized_end=270
  _CLEARCACHEREQUEST._serialized_start=272
  _CLEARCACHEREQUEST._serialized_end=305
  _CLEARCACHERESPONSE._serialized_start=307
  _CLEARCACHERESPONSE._serialized_end=341
  _FILEMANAGESERVICE._serialized_start=344
  _FILEMANAGESERVICE._serialized_end=481
# @@protoc_insertion_point(module_scope)
